name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Login to private container registry'
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        login-server: ${{ secrets.REGISTRY_URL }}
        
    - name: 'Setup docker build'
      uses: docker/setup-buildx-action@v3

    - name: 'Build docker image'
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: latest
        build-args: |
          GIT_COMMIT=${{github.sha}}
          GIT_BRANCH=${{github.ref}}
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        
