name: 'Pull Request'

on:
  pull_request:
    branches: [ "main" ]

jobs:

  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 'Set up Go'
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...
      shell: bash

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...
      shell: bash

    - name: Run golint
      uses: golangci/golangci-lint-action@v3.6.0

    - name: Build
      run: make compile ENVIRONMENT=production
      
    - name: Test
      run: make test ENVIRONENT=production
